# Generated by Django 4.2.1 on 2023-06-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.BigIntegerField(max_length=20)),
            ],
            options={
                'db_table': 'aaa',
            },
        ),
        migrations.DeleteModel(
            name='hello',
        ),
    ]
